services:
  simulator:
    build: .
    container_name: cm4000_simulator
    ports:
      - "5020:5020"  # Modbus TCP
      - "5021:5021"  # Control TCP
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: influxdb_v2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=ipset
      - DOCKER_INFLUXDB_INIT_BUCKET=cm4000_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - ./init-influxdb.sh:/docker-entrypoint-initdb.d/init-influxdb.sh:ro
    restart: unless-stopped

  adquisidor:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: cm4000_adquisidor
    depends_on:
      - simulator
      - influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    user: "root"
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - influxdb
    restart: unless-stopped



volumes:
  influxdb_data:
