default_config:



lovelace:
  resource_mode: yaml
  dashboards:
    lovelace:
      mode: yaml
      filename: ui-lovelace.yaml
      title: CM4000 Dashboard
      icon: mdi:flash
      show_in_sidebar: true

automation: !include automations.yaml

sensor:
  - platform: influxdb
    api_version: 2
    ssl: false
    host: influxdb
    port: 8086
    token: my-super-secret-auth-token
    organization: ipset
    bucket: cm4000_data
    queries_flux:
      - name: "CM4000 Voltage Phase A"
        range_start: "-1m"
        unit_of_measurement: "V"
        query: >
          filter(fn: (r) => r["_measurement"] == "cm4000_voltage_ln" and r["_field"] == "Vln_a")
          |> last()
          |> keep(columns: ["_value"])
      - name: "CM4000 Current Phase A"
        range_start: "-1m"
        unit_of_measurement: "A"
        query: >
          filter(fn: (r) => r["_measurement"] == "cm4000_current" and r["_field"] == "I_a")
          |> last()
          |> keep(columns: ["_value"])
      - name: "CM4000 Power Factor"
        range_start: "-1m"
        unit_of_measurement: ""
        query: >
          filter(fn: (r) => r["_measurement"] == "cm4000_power_factor" and r["_field"] == "PF_tot")
          |> last()
          |> keep(columns: ["_value"])
      - name: "CM4000 THD Voltage Phase A"
        range_start: "-1m"
        unit_of_measurement: "%"
        query: >
          filter(fn: (r) => r["_measurement"] == "cm4000_thd" and r["_field"] == "THD_V_a")
          |> last()
          |> keep(columns: ["_value"])
      - name: "CM4000 THD Current Phase A"
        range_start: "-1m"
        unit_of_measurement: "%"
        query: >
          filter(fn: (r) => r["_measurement"] == "cm4000_thd" and r["_field"] == "THD_I_a")
          |> last()
          |> keep(columns: ["_value"])
      - name: "CM4000 Max Demand kW"
        range_start: "-1m"
        unit_of_measurement: "kW"
        query: >
          filter(fn: (r) => r["_measurement"] == "cm4000_power_active" and r["_field"] == "kW_tot")
          |> last()
          |> keep(columns: ["_value"])
